name: push_gopal_checks

on: 
 push:
   branches:
     - feature/v1

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: pull code
        uses: actions/checkout@v4
        
      - name: ls repo
        run: ls -la
  
  deploy:
    runs-on: ubuntu-latest 
    needs: build

    steps:
      - name: pull code
        run: echo "deploying code"
